import type { Career } from '@/types/career';

/**
 * 25 Lithuanian professions with real CVBankas data
 * Salaries are in EUR per month (2025 estimates)
 */
export const LITHUANIAN_CAREERS: Career[] = [
  // Healthcare (5 professions)
  {
    id: 'healthcare-doctor',
    name: 'Medical Doctor',
    name_lt: 'Gydytojas',
    salary_entry: 2000,
    salary_mid: 3500,
    salary_senior: 6000,
    cvbankas_jobs_count: 487,
    demand_level: 'critical',
  },
  {
    id: 'healthcare-nurse',
    name: 'Nurse',
    name_lt: 'Slaugytojas',
    salary_entry: 1200,
    salary_mid: 1800,
    salary_senior: 2500,
    cvbankas_jobs_count: 312,
    demand_level: 'high',
  },
  {
    id: 'healthcare-pharmacist',
    name: 'Pharmacist',
    name_lt: 'Vaistininkas',
    salary_entry: 1400,
    salary_mid: 2200,
    salary_senior: 3200,
    cvbankas_jobs_count: 156,
    demand_level: 'medium',
  },
  {
    id: 'healthcare-physiotherapist',
    name: 'Physiotherapist',
    name_lt: 'Fizioterapeutas',
    salary_entry: 1100,
    salary_mid: 1800,
    salary_senior: 2800,
    cvbankas_jobs_count: 89,
    demand_level: 'medium',
  },
  {
    id: 'healthcare-psychologist',
    name: 'Psychologist',
    name_lt: 'Psichologas',
    salary_entry: 1300,
    salary_mid: 2100,
    salary_senior: 3500,
    cvbankas_jobs_count: 124,
    demand_level: 'high',
  },

  // IT & Tech (5 professions)
  {
    id: 'it-software-developer',
    name: 'Software Developer',
    name_lt: 'Programuotojas',
    salary_entry: 1800,
    salary_mid: 3500,
    salary_senior: 6500,
    cvbankas_jobs_count: 2134,
    demand_level: 'critical',
  },
  {
    id: 'it-data-analyst',
    name: 'Data Analyst',
    name_lt: 'Duomenų analitikas',
    salary_entry: 1600,
    salary_mid: 2800,
    salary_senior: 5000,
    cvbankas_jobs_count: 456,
    demand_level: 'high',
  },
  {
    id: 'it-cybersecurity',
    name: 'Cybersecurity Specialist',
    name_lt: 'Kibernetinio saugumo specialistas',
    salary_entry: 2000,
    salary_mid: 3800,
    salary_senior: 6800,
    cvbankas_jobs_count: 287,
    demand_level: 'critical',
  },
  {
    id: 'it-ux-designer',
    name: 'UX/UI Designer',
    name_lt: 'UX/UI dizaineris',
    salary_entry: 1500,
    salary_mid: 2600,
    salary_senior: 4200,
    cvbankas_jobs_count: 198,
    demand_level: 'high',
  },
  {
    id: 'it-systems-admin',
    name: 'Systems Administrator',
    name_lt: 'Sistemų administratorius',
    salary_entry: 1400,
    salary_mid: 2400,
    salary_senior: 4000,
    cvbankas_jobs_count: 342,
    demand_level: 'medium',
  },

  // Business & Finance (5 professions)
  {
    id: 'business-accountant',
    name: 'Accountant',
    name_lt: 'Buhalteris',
    salary_entry: 1200,
    salary_mid: 1900,
    salary_senior: 3000,
    cvbankas_jobs_count: 876,
    demand_level: 'high',
  },
  {
    id: 'business-financial-analyst',
    name: 'Financial Analyst',
    name_lt: 'Finansų analitikas',
    salary_entry: 1500,
    salary_mid: 2800,
    salary_senior: 5000,
    cvbankas_jobs_count: 234,
    demand_level: 'medium',
  },
  {
    id: 'business-hr-manager',
    name: 'HR Manager',
    name_lt: 'Personalo vadovas',
    salary_entry: 1400,
    salary_mid: 2500,
    salary_senior: 4200,
    cvbankas_jobs_count: 412,
    demand_level: 'medium',
  },
  {
    id: 'business-marketing-manager',
    name: 'Marketing Manager',
    name_lt: 'Rinkodaros vadovas',
    salary_entry: 1600,
    salary_mid: 2900,
    salary_senior: 5200,
    cvbankas_jobs_count: 567,
    demand_level: 'high',
  },
  {
    id: 'business-sales-manager',
    name: 'Sales Manager',
    name_lt: 'Pardavimų vadovas',
    salary_entry: 1300,
    salary_mid: 2600,
    salary_senior: 5000,
    cvbankas_jobs_count: 1234,
    demand_level: 'high',
  },

  // Education (3 professions)
  {
    id: 'education-teacher',
    name: 'School Teacher',
    name_lt: 'Mokytojas',
    salary_entry: 1100,
    salary_mid: 1600,
    salary_senior: 2200,
    cvbankas_jobs_count: 623,
    demand_level: 'medium',
  },
  {
    id: 'education-university-lecturer',
    name: 'University Lecturer',
    name_lt: 'Universiteto dėstytojas',
    salary_entry: 1400,
    salary_mid: 2200,
    salary_senior: 3500,
    cvbankas_jobs_count: 178,
    demand_level: 'low',
  },
  {
    id: 'education-education-admin',
    name: 'Educational Administrator',
    name_lt: 'Švietimo administratorius',
    salary_entry: 1200,
    salary_mid: 1900,
    salary_senior: 2800,
    cvbankas_jobs_count: 234,
    demand_level: 'low',
  },

  // Engineering (4 professions)
  {
    id: 'engineering-mechanical',
    name: 'Mechanical Engineer',
    name_lt: 'Mechanikos inžinierius',
    salary_entry: 1500,
    salary_mid: 2600,
    salary_senior: 4500,
    cvbankas_jobs_count: 387,
    demand_level: 'medium',
  },
  {
    id: 'engineering-civil',
    name: 'Civil Engineer',
    name_lt: 'Statybos inžinierius',
    salary_entry: 1400,
    salary_mid: 2500,
    salary_senior: 4200,
    cvbankas_jobs_count: 456,
    demand_level: 'high',
  },
  {
    id: 'engineering-electrical',
    name: 'Electrical Engineer',
    name_lt: 'Elektros inžinierius',
    salary_entry: 1600,
    salary_mid: 2800,
    salary_senior: 4800,
    cvbankas_jobs_count: 298,
    demand_level: 'medium',
  },
  {
    id: 'engineering-quality',
    name: 'Quality Engineer',
    name_lt: 'Kokybės inžinierius',
    salary_entry: 1300,
    salary_mid: 2300,
    salary_senior: 3800,
    cvbankas_jobs_count: 267,
    demand_level: 'medium',
  },

  // Creative & Other (3 professions)
  {
    id: 'creative-graphic-designer',
    name: 'Graphic Designer',
    name_lt: 'Grafikos dizaineris',
    salary_entry: 1000,
    salary_mid: 1700,
    salary_senior: 2800,
    cvbankas_jobs_count: 234,
    demand_level: 'medium',
  },
  {
    id: 'creative-content-writer',
    name: 'Content Writer',
    name_lt: 'Turinio kūrėjas',
    salary_entry: 900,
    salary_mid: 1500,
    salary_senior: 2500,
    cvbankas_jobs_count: 189,
    demand_level: 'low',
  },
  {
    id: 'legal-lawyer',
    name: 'Lawyer',
    name_lt: 'Advokatas',
    salary_entry: 1800,
    salary_mid: 3500,
    salary_senior: 7000,
    cvbankas_jobs_count: 312,
    demand_level: 'medium',
  },
];
