/**
 * AQABZA - 40 Kategorijos
 * 40 CVBankas Darbo Profesijų
 * Kiekviena kategorija turi 20 el. laiškų situacijų = 800 iš viso
 */

export interface Category {
  id: string;
  name: string; // Lietuviškas pavadinimas
  nameEn: string; // Angliškas pavadinimas (nuorodai)
  icon: string; // Emoji
  description: string; // Lietuviškas aprašymas
  emailCount: number; // Visada 20
  color: string; // UI temavimui
}

// ==========================================
// 40 CVBANKAS DARBO PROFESIJŲ
// ==========================================

export const ALL_CATEGORIES: Category[] = [
  {
    id: 'it-programuotojas',
    name: 'IT Programuotojas',
    nameEn: 'Software Developer',
    icon: '💻',
    description: 'Kodo peržiūros, klaidų pranešimai, komandinio darbo komunikacija.',
    emailCount: 20,
    color: 'blue',
  },
  {
    id: 'marketingo-specialistas',
    name: 'Marketingo specialistas',
    nameEn: 'Marketing Specialist',
    icon: '📊',
    description: 'Kampanijų ataskaitos, klientų pasiūlymai, socialinių tinklų strategijos.',
    emailCount: 20,
    color: 'pink',
  },
  {
    id: 'klientu-aptarnavimas',
    name: 'Klientų aptarnavimas',
    nameEn: 'Customer Service',
    icon: '📞',
    description: 'Skundų sprendimas, užklausų atsakymai, klientų raminimas.',
    emailCount: 20,
    color: 'green',
  },
  {
    id: 'buhalteris',
    name: 'Buhalteris',
    nameEn: 'Accountant',
    icon: '🧮',
    description: 'Sąskaitų faktūrų klausimai, mokesčių ataskaitos, finansiniai pranešimai.',
    emailCount: 20,
    color: 'yellow',
  },
  {
    id: 'hr-vadybininkas',
    name: 'HR vadybininkas',
    nameEn: 'HR Manager',
    icon: '👥',
    description: 'Darbuotojų įdarbinimas, atostogų prašymai, darbo sutarčių klausimai.',
    emailCount: 20,
    color: 'purple',
  },
  {
    id: 'pardavimo-vadybininkas',
    name: 'Pardavimo vadybininkas',
    nameEn: 'Sales Manager',
    icon: '💼',
    description: 'Pasiūlymų siuntimas, derybos su klientais, sutarčių derinimas.',
    emailCount: 20,
    color: 'orange',
  },
  {
    id: 'logistikos-koordinatorius',
    name: 'Logistikos koordinatorius',
    nameEn: 'Logistics Coordinator',
    icon: '🚚',
    description: 'Siuntų sekimas, pristatymo grafikai, tiekėjų komunikacija.',
    emailCount: 20,
    color: 'cyan',
  },
  {
    id: 'grafinis-dizaineris',
    name: 'Grafinis dizaineris',
    nameEn: 'Graphic Designer',
    icon: '🎨',
    description: 'Projektų aptarimas, pakeitimų prašymai, kūrybinės koncepcijos.',
    emailCount: 20,
    color: 'pink',
  },
  {
    id: 'mokytojas',
    name: 'Mokytojas',
    nameEn: 'Teacher',
    icon: '👨‍🏫',
    description: 'Tėvų informavimas, pažymių paaiškinimas, susitikimų organizavimas.',
    emailCount: 20,
    color: 'blue',
  },
  {
    id: 'slaugytojas',
    name: 'Slaugytojas',
    nameEn: 'Nurse',
    icon: '👩‍⚕️',
    description: 'Pacientų priežiūros ataskaitos, vaistų užsakymai, pamainų koordinavimas.',
    emailCount: 20,
    color: 'red',
  },
  {
    id: 'mechanikas',
    name: 'Mechanikas',
    nameEn: 'Mechanic',
    icon: '🔧',
    description: 'Remonto ataskaitos, dalių užsakymai, klientų informavimas.',
    emailCount: 20,
    color: 'gray',
  },
  {
    id: 'elektrikas',
    name: 'Elektrikas',
    nameEn: 'Electrician',
    icon: '⚡',
    description: 'Gedimų pranešimai, darbų sąmatos, saugos instrukcijos.',
    emailCount: 20,
    color: 'yellow',
  },
  {
    id: 'virejas-kulinaras',
    name: 'Virėjas / Kulinaras',
    nameEn: 'Chef / Cook',
    icon: '👨‍🍳',
    description: 'Meniu kūrimas, produktų užsakymai, maisto alergijų valdymas.',
    emailCount: 20,
    color: 'orange',
  },
  {
    id: 'prekybos-centro-vadovas',
    name: 'Prekybos centro vadovas',
    nameEn: 'Retail Manager',
    icon: '🏬',
    description: 'Inventoriaus valdymas, darbuotojų grafikai, klientų pasitenkinimas.',
    emailCount: 20,
    color: 'green',
  },
  {
    id: 'nekilnojamo-turto-agentas',
    name: 'Nekilnojamo turto agentas',
    nameEn: 'Real Estate Agent',
    icon: '🏡',
    description: 'Apžiūrų organizavimas, pasiūlymų siuntimas, derybos.',
    emailCount: 20,
    color: 'purple',
  },
  {
    id: 'banko-darbuotojas',
    name: 'Banko darbuotojas',
    nameEn: 'Bank Teller',
    icon: '🏦',
    description: 'Klientų užklausos, paskolų paaiškinimai, sąskaitų klausimai.',
    emailCount: 20,
    color: 'blue',
  },
  {
    id: 'statybos-vadovas',
    name: 'Statybos vadovas',
    nameEn: 'Construction Manager',
    icon: '🏗️',
    description: 'Projekto ataskaitos, rangovo komunikacija, saugos standartai.',
    emailCount: 20,
    color: 'orange',
  },
  {
    id: 'vaistininkas',
    name: 'Vaistininkas',
    nameEn: 'Pharmacist',
    icon: '💊',
    description: 'Vaistų užsakymai, pacientų konsultacijos, receptų klausimai.',
    emailCount: 20,
    color: 'green',
  },
  {
    id: 'advokatas',
    name: 'Advokatas',
    nameEn: 'Lawyer',
    icon: '⚖️',
    description: 'Teisinio patarimo prašymai, dokumentų paruošimas, bylos atnaujinimai.',
    emailCount: 20,
    color: 'gray',
  },
  {
    id: 'architektas',
    name: 'Architektas',
    nameEn: 'Architect',
    icon: '📐',
    description: 'Dizaino pasiūlymai, projekto keitimai, klientų lūkesčių valdymas.',
    emailCount: 20,
    color: 'purple',
  },
  {
    id: 'turisto-gidas',
    name: 'Turisto gidas',
    nameEn: 'Tour Guide',
    icon: '🗺️',
    description: 'Ekskursijų organizavimas, klientų užklausos, maršrutų derinimas.',
    emailCount: 20,
    color: 'cyan',
  },
  {
    id: 'fotografas',
    name: 'Fotografas',
    nameEn: 'Photographer',
    icon: '📷',
    description: 'Fotosesijų derinimas, nuotraukų pristatymas, pakeitimų prašymai.',
    emailCount: 20,
    color: 'pink',
  },
  {
    id: 'zurnalistas',
    name: 'Žurnalistas',
    nameEn: 'Journalist',
    icon: '📰',
    description: 'Interviu prašymai, straipsnių redagavimas, šaltinių patvirtinimas.',
    emailCount: 20,
    color: 'blue',
  },
  {
    id: 'socialinis-darbuotojas',
    name: 'Socialinis darbuotojas',
    nameEn: 'Social Worker',
    icon: '🤲',
    description: 'Atvejų valdymas, šeimų palaikymas, išteklių koordinavimas.',
    emailCount: 20,
    color: 'green',
  },
  {
    id: 'projektu-vadovas',
    name: 'Projektų vadovas',
    nameEn: 'Project Manager',
    icon: '📋',
    description: 'Pažangos ataskaitos, komandos koordinavimas, terminų valdymas.',
    emailCount: 20,
    color: 'orange',
  },
  {
    id: 'duomenu-analitikas',
    name: 'Duomenų analitikas',
    nameEn: 'Data Analyst',
    icon: '📈',
    description: 'Ataskaitų pateikimas, duomenų aiškinimas, įžvalgų dalijimasis.',
    emailCount: 20,
    color: 'purple',
  },
  {
    id: 'personalinis-treneris',
    name: 'Personalinis treneris',
    nameEn: 'Personal Trainer',
    icon: '💪',
    description: 'Treniruočių planai, klientų pažanga, mitybos patarimai.',
    emailCount: 20,
    color: 'red',
  },
  {
    id: 'renginiu-planavimas',
    name: 'Renginių planuotojas',
    nameEn: 'Event Planner',
    icon: '🎉',
    description: 'Renginių organizavimas, tiekėjų koordinavimas, biudžeto valdymas.',
    emailCount: 20,
    color: 'pink',
  },
  {
    id: 'vertejas',
    name: 'Vertėjas',
    nameEn: 'Translator',
    icon: '🌐',
    description: 'Vertimo užklausos, terminų derinimas, aiškumo užtikrinimas.',
    emailCount: 20,
    color: 'blue',
  },
  {
    id: 'video-redaktorius',
    name: 'Video redaktorius',
    nameEn: 'Video Editor',
    icon: '🎬',
    description: 'Projekto reikalavimai, pakeitimų įgyvendinimas, pristatymo terminai.',
    emailCount: 20,
    color: 'purple',
  },
  {
    id: 'rinkodaros-tyrejas',
    name: 'Rinkodaros tyrėjas',
    nameEn: 'Market Researcher',
    icon: '🔍',
    description: 'Tyrimų ataskaitos, vartotojų apklausos, konkurencijos analizė.',
    emailCount: 20,
    color: 'blue',
  },
  {
    id: 'produkto-vadovas',
    name: 'Produkto vadovas',
    nameEn: 'Product Manager',
    icon: '📱',
    description: 'Funkcijų prioritizavimas, klientų atsiliepimai, išleidimo planavimas.',
    emailCount: 20,
    color: 'green',
  },
  {
    id: 'konsultantas',
    name: 'Verslo konsultantas',
    nameEn: 'Business Consultant',
    icon: '💡',
    description: 'Klientų konsultacijos, sprendimų pasiūlymai, strategijos kūrimas.',
    emailCount: 20,
    color: 'orange',
  },
  {
    id: 'it-palaikymas',
    name: 'IT palaikymo specialistas',
    nameEn: 'IT Support Specialist',
    icon: '🖥️',
    description: 'Techninės problemos, vartotojų pagalba, sistemų priežiūra.',
    emailCount: 20,
    color: 'cyan',
  },
  {
    id: 'vidaus-auditorius',
    name: 'Vidaus auditorius',
    nameEn: 'Internal Auditor',
    icon: '📑',
    description: 'Auditų ataskaitos, rizikos valdymas, atitikties patikrinimas.',
    emailCount: 20,
    color: 'gray',
  },
  {
    id: 'turinio-kurėjas',
    name: 'Turinio kūrėjas',
    nameEn: 'Content Creator',
    icon: '✍️',
    description: 'Straipsnių rašymas, socialinių tinklų valdymas, SEO optimizavimas.',
    emailCount: 20,
    color: 'pink',
  },
  {
    id: 'testavimo-inzinierius',
    name: 'Testavimo inžinierius',
    nameEn: 'QA Engineer',
    icon: '🔬',
    description: 'Klaidų pranešimai, testavimo planai, kokybės užtikrinimas.',
    emailCount: 20,
    color: 'purple',
  },
  {
    id: 'administracijos-vadovas',
    name: 'Administracijos vadovas',
    nameEn: 'Office Manager',
    icon: '🗂️',
    description: 'Biuro valdymas, tiekėjų koordinavimas, išteklių planavimas.',
    emailCount: 20,
    color: 'yellow',
  },
  {
    id: 'finansu-analitikas',
    name: 'Finansų analitikas',
    nameEn: 'Financial Analyst',
    icon: '💹',
    description: 'Finansinės ataskaitos, biudžeto prognozės, investicijų analizė.',
    emailCount: 20,
    color: 'green',
  },
  {
    id: 'klientu-sekmės-vadovas',
    name: 'Klientų sėkmės vadovas',
    nameEn: 'Customer Success Manager',
    icon: '🤝',
    description: 'Klientų įsitraukimas, pasitenkinimo stebėjimas, atsinaujinimo valdymas.',
    emailCount: 20,
    color: 'blue',
  },
];

// ==========================================
// PAGALBINĖS FUNKCIJOS
// ==========================================

export const getCategoryById = (id: string): Category | undefined => {
  return ALL_CATEGORIES.find((cat) => cat.id === id);
};

export const getTotalEmailCount = (): number => {
  return ALL_CATEGORIES.reduce((sum, cat) => sum + cat.emailCount, 0); // 800
};

// Spalvų susiejimas UI
export const CATEGORY_COLORS = {
  blue: 'from-blue-500 to-blue-600',
  green: 'from-green-500 to-green-600',
  red: 'from-red-500 to-red-600',
  yellow: 'from-yellow-500 to-yellow-600',
  purple: 'from-purple-500 to-purple-600',
  pink: 'from-pink-500 to-pink-600',
  orange: 'from-orange-500 to-orange-600',
  cyan: 'from-cyan-500 to-cyan-600',
  gray: 'from-gray-500 to-gray-600',
  indigo: 'from-indigo-500 to-indigo-600',
};
